# окружений в котором запускают
env: "local" # local, dev, prod

# путь до файла в котором будет храниться бд
storage_path: "./storage/storage.db"

# настройки http сервера
http_server:
  address: "localhost:8082"
  # время на чтение запроса и такое же время на отправку ответа
  timeout: 4s
  # время жизни соединения с клиентом, чтобы заного не создвать соединение
  # если будет повторный запрос от тогоже клиента
  idle_timeout: 60s
  user: "myuser"
  password: "mypassword"
